# gan_v2.yaml

experiment_name: gan_v2

dataset:
  name: cora
  data_dir: data/cora/

model:
  type: gan               # 使用 GAN 架构
  use_agent: true         # 启用智能节点
  use_mock_llm: false     # 启用真实推理
  max_steps: 5            # 每个节点的最大迭代步数
  prompt_style: condensed # 假设 v2 使用 condensed prompt 结构

llm:
  backend: remote
  api_base: http://localhost:8001/v1
  model: llama-3.1-8b-instruct
  temperature: 0.7
  max_tokens: 128
  top_p: 0.95

inference:
  allow_retrieve_all: true     # 可从全图检索（用于 v2 扩展版本）
  neighbor_first: true         # 优先使用邻居信息
  retrieve_top_k: 3            # 每次 retrieve 返回几个节点

output:
  dir: results/gan_v2/
  save_predictions: true
  save_logits: false
  log_level: info
